version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - "80:8080"
    networks:
      - my_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.back
    ports:
      - "5000:5000"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
